felipeangelimvieira/prophetverse

src/prophetverse/effects/__init__.py
src/prophetverse/effects/base.py
src/prophetverse/effects/effect_apply.py
src/prophetverse/effects/hill.py
src/prophetverse/effects/linear.py
src/prophetverse/effects/log.py

Add missing `__init__.py` file to effects module.
Closes #60

[MNT] Add __init__ to effects

---

.github/workflows/ci.yaml

Adds a matrix of common OS and python versions for the CI workflow for testing.

[MNT] OS and python version matrix for CI workflow

---

mkdocs.yml

Add versioning to Prophetverse's documentation

[DOC] Add versioning to mkdocs

---

docs/README.md
src/prophetverse/effects/base.py
tests/effects/test_base.py

Update bad docstrings in BaseEffect

[MNT] Update BaseEffect docstrings

---

pyproject.toml
src/prophetverse/effects/base.py
src/prophetverse/sktime/univariate.py

Add deprecation warnings to the package, before releasing 0.4.0

[MNT] Add deprecation warnings

---

docs/development/development-guide.md
docs/effects-api.md
docs/examples/univariate.ipynb
docs/the-theory.md

- bug fix poetry dev installation tutorial
- add some hyperlinks do docs
- delete not used imports at jupyter example
- enhance explanation of equation (term by term)

[DOC] Hyperlinks, fix poetry dev installation tutorial

---

src/prophetverse/sktime/multivariate.py
src/prophetverse/sktime/univariate.py

[DOC] Add example to docstrings of sktime estimators

---

src/prophetverse/effects/trend/piecewise.py
tests/trend/test_piecewise.py

[FIX] Fix trend design matrix

---

src/prophetverse/effects/base.py
src/prophetverse/effects/lift_experiment.py
src/prophetverse/sktime/base.py
tests/effects/test_base.py

[ENH] Optional `_fit` for effects

---

src/prophetverse/effects/adstock.py
tests/effects/test_adstock.py

[ENH] Add geometric adstock effect

---

src/prophetverse/effects/__init__.py
src/prophetverse/effects/chain.py
tests/effects/test_chain.py

[ENH] Add chain effect

---

pyproject.toml

[MNT] Set ipymd as optional dependency

---

src/prophetverse/__init__.py
src/prophetverse/engine/mcmc.py
src/prophetverse/engine/utils.py
src/prophetverse/exc.py
tests/engine/test_utils.py

[ENH] MCMC convergence check

---

src/prophetverse/engine/mcmc.py

[ENH] Take the number of chains into account in MCMCInferenceEngine._predict

---

src/prophetverse/sktime/base.py
tests/sktime/test_base.py

[ENH] Use property decorator for posterior samples

---

.github/workflows/ci.yaml

[MNT] Abort if new PR is detected

---

src/prophetverse/sktime/base.py
tests/engine/test_utils.py
tests/experimental/test_simulate.py

[FIX] Cast X to inner mtype in custom public methods

---

pyproject.toml

Prepare for releasing 0.6.0. Will wait until sktime's 0.37.0 since this one introduces breaking changes and there's a PR that will set an upper bound <0.6. 
@tingiskhan your changes will be included in this release.

[MNT] Bump to 0.6.0

---

src/prophetverse/effects/adstock.py
src/prophetverse/effects/base.py
src/prophetverse/effects/chain.py
src/prophetverse/effects/exact_likelihood.py
src/prophetverse/effects/fourier.py
src/prophetverse/effects/hill.py
src/prophetverse/effects/lift_likelihood.py
src/prophetverse/effects/linear.py
src/prophetverse/effects/log.py
src/prophetverse/effects/trend/piecewise.py
src/prophetverse/sktime/_expand_column_per_level.py
tests/effects/test_all_effects.py
tests/effects/test_chain.py
tests/effects/test_hill.py
tests/effects/test_linear.py
tests/effects/test_log.py

Closes #206 
Closes #202 
This PR focus on improving the handling of effect parameters, enhancing the `ChainedEffects` class, and adding test parameter generation for effects. These updates improve code clarity, maintainability, and testing capabilities.
* Updated parameter initialization across multiple effect classes (`adstock.py`, `hill.py`, `linear.py`, `log.py`, `piecewise.py`) to use private attributes (e.g., `_decay_prior`, `_half_max_prior`) for default distributions. This ensures consistency and avoids modifying public attributes directly. [[1]](diffhunk://#diff-590cec66b17c5426ca11cd2c4c546d790e5008ffdd714ce68dcfa167299b0b25L37-R44) [[2]](diffhunk://#diff-590cec66b17c5426ca11cd2c4c546d790e5008ffdd714ce68dcfa167299b0b25L95-R96) …

[BUG] Fix GeometricAdstock and make every effect skbase-compliant

---

src/prophetverse/sktime/base.py

Removing the `model` method caused derived classes to fail. Instead of enforcing inference on `model_func` we default to it instead if not overridden.
See #229

[BUG] Reverts the removal of the `model` method

---

.github/workflows/ci.yaml
.github/workflows/docs.yml

[MNT] Avoiding pushing docs to latest if the version is a release candidate

---

docs/_quarto.yml
docs/prompts/custom_effects.qmd
extension_templates/effect.py

[ENH] Update extension template
